"use client";
import { Unna } from "next/font/google";
import MainHeader from "@/components/MainHeader";
import MainFooter from "@/components/MainFooter";
// Variable for the font
const pUnna = Unna({ weight: "400", subsets: ["latin"] });
/**
 * Meta data for the app
 */
export const metadata = {
  title: "Organization",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className={pUnna.className}>
      <MainHeader />
      {children}
      <MainFooter />
    </div>
  );
}
