import "./globals.css";

import { Cormorant, Frank_Ruhl_Libre, Oswald, PT_Sans, Poppins, Raleway, Unna } from "next/font/google";

import MainFooter from "@/components/MainFooter";
/**
 * @author Felix Orinda
 * @email forinda82@gmail.com
 * @create date 2023-07-06 23:45:56
 * @modify date 2023-07-06 23:45:56
 * @desc [Base layout for the app]
 */
import MainHeader from "@/components/MainHeader";

// Variable for the font
const pnormal = PT_Sans({ weight: "400", subsets: ["latin"] });
const pPoppins = Poppins({ weight: "400", subsets: ["latin"] });
const pRaleway = Raleway({ weight: "400", subsets: ["latin"] });
const pOswald = Oswald({ weight: "400", subsets: ["latin"] });
const pFrank_Ruhl_Libre = Frank_Ruhl_Libre({ weight: "400", subsets: ["latin"] });
const pCormorant = Cormorant({ weight: "400", subsets: ["latin"] });
const pUnna = Unna({ weight: "400", subsets: ["latin"] });
/**
 * Meta data for the app
 */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={pUnna.className}>
        <MainHeader />
        {children}
        <MainFooter />
      </body>
    </html>
  );
}
