// data/surveyData.ts

import { Question, SurveySchema } from "@/lib/types/survey";

export const surveyQuestions: Question[] = [
  {
    id: 1,
    question: "Age",
    type: "number",
    required: true,
    placeholder: "Enter your age",
  },
  {
    id: 2,
    question: "Gender",
    type: "choice",
    required: true,
    options: ["Male", "Female", "Other", "Prefer not to say"],
    multiple: false,
  },
  {
    id: 3,
    question: "Age bracket",
    type: "choice",
    required: true,
    options: ["Under 18", "18-24", "25-34", "35-44", "45-54", "55+"],
    multiple: false,
  },
  {
    id: 4,
    question: "Was ticket fairly priced?",
    type: "choice",
    required: true,
    options: ["Very fair", "Fair", "Neutral", "Unfair", "Very unfair"],
    multiple: false,
  },
  {
    id: 5,
    question: "Employment Status",
    type: "choice",
    required: true,
    options: ["Self-employed", "Employee", "Student", "Unemployed", "Retired"],
    multiple: false,
  },
  {
    id: 6,
    question: "How satisfied with vendors?",
    type: "choice",
    required: true,
    options: [
      "Very satisfied",
      "Satisfied",
      "Neutral",
      "Dissatisfied",
      "Very dissatisfied",
    ],
    multiple: false,
  },
  {
    id: 7,
    question: "How satisfied with entry process?",
    type: "choice",
    required: true,
    options: [
      "Very satisfied",
      "Satisfied",
      "Neutral",
      "Dissatisfied",
      "Very dissatisfied",
    ],
    multiple: false,
  },
  {
    id: 8,
    question: "Was it value for money?",
    type: "choice",
    required: true,
    options: [
      "Excellent value",
      "Good value",
      "Fair value",
      "Poor value",
      "Very poor value",
    ],
    multiple: false,
  },
  {
    id: 9,
    question: "What can be done better?",
    type: "text",
    required: false,
    placeholder: "Please share your suggestions...",
    multiline: true,
  },
  {
    id: 10,
    question: "How did you get to know about the event?",
    type: "choice",
    required: true,
    options: [
      "Social media",
      "Friend/Family",
      "Email",
      "Website",
      "Radio",
      "TV",
      "Newspaper",
      "Other",
    ],
    multiple: true,
    other: true,
  },
  {
    id: 11,
    question: "How many rugby events have you attended in the last 1 year?",
    type: "choice",
    required: true,
    options: ["0", "1-2", "3-5", "6-10", "10+"],
    multiple: false,
  },
  {
    id: 12,
    question: "Are you a supporter or fan of rugby events?",
    type: "choice",
    required: true,
    options: ["Yes", "No", "Casual fan"],
    multiple: false,
  },
  {
    id: 13,
    question: "Which event did you attend?",
    type: "choice",
    required: true,
    options: [
      "HSBC Sevens",
      "Local League",
      "International Test Match",
      "School/University",
      "Other",
    ],
    multiple: true,
    other: true,
  },
  {
    id: 14,
    question:
      "If you haven't attended any event, did HSBC meet your expectations?",
    type: "choice",
    required: false,
    options: [
      "Exceeded expectations",
      "Met expectations",
      "Below expectations",
      "N/A - I attended",
    ],
    multiple: false,
    conditional: {
      dependsOn: 11,
      condition: (answer) => answer === "0",
    },
  },
  {
    id: 15,
    question: "Do you want to be informed about future events?",
    type: "contact",
    required: false,
    fields: [
      {
        name: "phone",
        label: "Phone Number",
        type: "tel",
        placeholder: "+254 XXX XXX XXX",
      },
      {
        name: "email",
        label: "Email Address",
        type: "email",
        placeholder: "your@email.com",
      },
    ],
  },
  {
    id: 16,
    question: "Which KRU channels do you follow?",
    type: "choice",
    required: false,
    options: [
      "None",
      "Instagram",
      "WhatsApp",
      "Facebook",
      "TikTok",
      "X (Twitter)",
    ],
    multiple: true,
    layout: "grid",
  },
];

export const surveySchema: SurveySchema = {
  metadata: {
    title: "Rugby Event Feedback Survey",
    description: "Help us improve future events",
    version: "1.0",
  },
  sections: [
    {
      id: "demographics",
      title: "Demographics",
      questions: [1, 2, 3, 5],
    },
    {
      id: "event_experience",
      title: "Event Experience",
      questions: [4, 6, 7, 8],
    },

    {
      id: "engagement",
      title: "Engagement",
      questions: [10, 11, 12, 13, 16],
    },
    {
      id: "feedback",
      title: "Feedback & Suggestions",
      questions: [9, 14],
    },
    {
      id: "contact",
      title: "Stay Connected",
      questions: [15],
    },
  ],
  questions: surveyQuestions,
};
