import {
  Roboto,
} from "next/font/google";

/**
 * @author Felix Orinda
 * @email forinda82@gmail.com
 * @create date 2023-07-06 23:45:56
 * @modify date 2023-07-06 23:45:56
 * @desc [Base layout for the app]
 */

// Variable for the font
const pRoboto = Roboto({ weight: "400", subsets: ["latin"] });
/**
 * Meta data for the app
 */
export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <main className={pRoboto.className}>{children}</main>;
}
